# Generated by Django 6.0 on 2025-12-21 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RideCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("UBER", "Uber"),
                            ("BOLT", "Bolt"),
                            ("YANGO", "Yango"),
                        ],
                        max_length=10,
                    ),
                ),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lng", models.FloatField()),
                ("response", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Ride Cache",
                "verbose_name_plural": "Ride Caches",
                "db_table": "ride_cache",
                "indexes": [
                    models.Index(
                        fields=[
                            "provider",
                            "pickup_lat",
                            "pickup_lng",
                            "dropoff_lat",
                            "dropoff_lng",
                        ],
                        name="ride_cache_provide_fe9162_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="ride_cache_expires_5b5565_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pickup_address", models.CharField(max_length=500)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lng", models.FloatField()),
                ("dropoff_address", models.CharField(max_length=500)),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lng", models.FloatField()),
                ("results", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Search History",
                "verbose_name_plural": "Search History",
                "db_table": "search_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="search_hist_user_id_3ea0ad_idx",
                    )
                ],
            },
        ),
    ]
