# Generated by Django 6.0 on 2026-03-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="stops",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
