# Generated by Django 6.0 on 2026-03-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0002_searchhistory_stops"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="pickup_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
